import { createHmac, createPublicKey, randomBytes, timingSafeEqual, type KeyObject } from "node:crypto";
import { constants, lstatSync } from "node:fs";
import { mkdir, mkdtemp, open, realpath, rm, type FileHandle } from "node:fs/promises";
import { spawn, type ChildProcess } from "node:child_process";
import { connect, Socket, type Socket as NodeSocket } from "node:net";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, relative, resolve, join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { BrokerError, canonicalJson, parseJsonUtf8Strict, sha256 } from "@mac-operator/contracts";
import { AppSandboxRunAdmission } from "./app-sandbox-run-admission.js";
import {
  createDescriptorHandoffSocketPair,
  sendDescriptorHandoff
} from "./descriptor-handoff-receiver.js";
import {
  getDescriptorPath,
  loadNativePeerAdapter,
  parsePeerCredentials,
  authorizePeerCredentials,
  type PeerProcessIdentity
} from "./peer-credentials.js";
import {
  validateRootHelperSnapshotProcessOwnershipSnapshot,
  validateRootHelperSnapshotProcessResult
} from "./root-helper-snapshot.js";
import { stageAppSandboxFilesystem, type AppSandboxFilesystemStage } from "./app-sandbox-filesystem.js";
import {
  BrokerNetworkProxy,
  BrokerNetworkProxyChannel,
  createBrokerNetworkProxyPolicy
} from "./network-proxy.js";
import { parseTaskNetworkDestination } from "./task-profile.js";
import {
  assertProcessPathIdentityStable,
  captureProcessPathIdentity,
  type ProcessExecutionResult,
  type ProcessOwnershipSnapshot
} from "./process-supervisor.js";
import { readMacOsReleaseArtifactSummary } from "./macos-release-preflight.js";
import {
  appSandboxHelperBundlePath,
  validateAppSandboxHelperReleaseEvidence,
  type AppSandboxHelperReleaseEvidence,
  type AppSandboxHelperReleaseExpectation
} from "./app-sandbox-helper-release.js";
import type { CodeSignatureExpectation } from "./macos-install-plan.js";
import type { AppSandboxTaskExecutionRequest, AppSandboxTaskExecutor, TaskRunnerPublicEnablement } from "./task-runner.js";

const APP_SANDBOX_REQUEST_DOMAIN = "mac-operator-app-sandbox-helper-v0.1\0";
const APP_SANDBOX_RESPONSE_DOMAIN = "mac-operator-app-sandbox-helper-response-v0.1\0";
const APP_SANDBOX_MECHANISM = "darwin-app-sandbox-helper-v1" as const;
const APP_SANDBOX_AUDIENCE = "mac-operator-app-sandbox-helper-v0.1" as const;
const APP_SANDBOX_SCHEMA_VERSION = "0.1" as const;
const MAX_RESPONSE_BYTES = 2 * 1024 * 1024 + 64 * 1024;
const MAX_HELPER_STDERR_BYTES = 64 * 1024;
const MAX_HELPER_STARTUP_MS = 5_000;
const MAX_TIMEOUT_MS = 600_000;
const KEY_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const DIGEST_PATTERN = /^[a-f0-9]{64}$/u;

export interface AppSandboxTaskExecutorCapability {
  schemaVersion: "0.1";
  mechanism: "darwin-app-sandbox-helper-v1";
  available: boolean;
  descriptorHandoff: "verified" | "unproven";
  helperAuthentication: "native-peer-and-hmac" | "unproven";
  helperContentIdentity: "verified" | "unproven";
  helperReleaseMode: "development-probe" | "production" | "unproven";
  productionRelease: "developer-id-notarized" | "unproven";
  attestationVerification: "native-ed25519" | "unproven";
  fixedInterpreter: "/bin/sh" | "unproven";
  scriptDescriptor: "verified" | "unproven";
  containerCwd: "verified" | "unproven";
  networkProxy: "broker-loopback-allowlist-v1" | "unproven";
  evidenceRef?: string;
}

export interface NativeAppSandboxTaskExecutorOptions {
  /** Explicit opt-in; the default remains unavailable. */
  enabled?: boolean;
  /** Independent host evidence gate; request data cannot supply it. */
  hostEvidenceAccepted?: boolean;
  /** Canonical, host-owned, signed App Sandbox helper executable. */
  helperPath: string;
  /** Canonical App Sandbox container Data directory owned by the Broker user. */
  containerRoot: string;
  /** Host-owned SHA-256 identity for the exact helper artifact to execute. */
  expectedHelperContentSha256?: string;
  /** Explicitly distinguish an ad-hoc physical probe from production use. */
  releaseMode?: "development-probe" | "production";
  /** Required when releaseMode is production; generated by the release preflight. */
  productionReleaseEvidence?: AppSandboxHelperReleaseEvidence;
  /** Host-owned Developer ID identity policy for production evidence. */
  productionReleaseSignature?: CodeSignatureExpectation;
  /** Key identity corresponding to the DescriptorSnapshot signer. */
  attestationKeyId: string;
  /** Raw 32-byte Ed25519 public key, or a Node public-key representation. */
  attestationPublicKey: Buffer | string | KeyObject;
  /** Optional additional verifier used before the native handoff. */
  attestationVerifier?: { verify(value: unknown): unknown };
  /** Independent physical evidence gate for the Broker-owned network channel. */
  networkEvidenceAccepted?: boolean;
  evidenceRef?: string;
  now?: () => number;
}

interface AppSandboxUnsignedEnvelope {
  schemaVersion: typeof APP_SANDBOX_SCHEMA_VERSION;
  mechanism: typeof APP_SANDBOX_MECHANISM;
  requestId: string;
  timestampMs: number;
  expiresAtMs: number;
  signedAttestation: AppSandboxTaskExecutionRequest["signedAttestation"];
  executionKind: "posix-sh-script";
  scriptContentSha256: string;
  args: readonly string[];
  environment: Readonly<Record<string, string>>;
  timeoutMs: number;
  outputCapBytes: number;
  networkChannelToken?: string;
}

interface AppSandboxSignedEnvelope extends AppSandboxUnsignedEnvelope {
  authenticationProof: string;
}

interface AppSandboxProcessEvent {
  kind: "process_started";
  requestId: string;
  snapshot: ProcessOwnershipSnapshot;
  eventProof: string;
}

interface ActiveHelperRun {
  child: ChildProcess;
  cancel: () => void;
}

interface SocketWithHandle extends Socket {
  _handle?: { fd?: unknown };
}

/** Disabled executor used by startup assembly when App Sandbox evidence is absent. */
export class DisabledAppSandboxTaskExecutor implements AppSandboxTaskExecutor {
  readonly available = false;
  readonly publicEnablement: TaskRunnerPublicEnablement = "unavailable";
  readonly capability: AppSandboxTaskExecutorCapability = Object.freeze({
    schemaVersion: "0.1",
    mechanism: "darwin-app-sandbox-helper-v1",
    available: false,
    descriptorHandoff: "unproven",
    helperAuthentication: "unproven",
    helperContentIdentity: "unproven",
    helperReleaseMode: "unproven",
    productionRelease: "unproven",
    attestationVerification: "unproven",
    fixedInterpreter: "unproven",
    scriptDescriptor: "unproven",
    containerCwd: "unproven",
    networkProxy: "unproven"
  });

  async run(
    _request: AppSandboxTaskExecutionRequest,
    _control: Pick<import("./task-runner.js").TaskExecutionControl, "timeoutMs" | "shouldCancel" | "onProcessStarted" | "onProcessOwnershipChanged">
  ): Promise<ProcessExecutionResult> {
    throw new BrokerError("POLICY_DENIED", "App Sandbox task execution is disabled");
  }

  async close(): Promise<void> {}
}

/**
 * Broker-side one-shot transport for the signed App Sandbox helper candidate.
 * It accepts only already-open descriptors and a fixed `/bin/sh` script mode;
 * host paths never enter the helper envelope.
 */
export class NativeAppSandboxTaskExecutor implements AppSandboxTaskExecutor {
  private readonly configuredAvailable: boolean;
  private readonly capabilityBase: AppSandboxTaskExecutorCapability;
  private readonly helperPath: string;
  private readonly containerRoot: string;
  private readonly expectedHelperContentSha256: string | undefined;
  private readonly releaseMode: "development-probe" | "production" | undefined;
  private readonly productionReleaseEvidence: AppSandboxHelperReleaseEvidence | undefined;
  private readonly attestationKeyId: string;
  private readonly attestationPublicKey: Buffer;
  private readonly attestationVerifier: NativeAppSandboxTaskExecutorOptions["attestationVerifier"];
  private readonly networkEvidenceAccepted: boolean;
  private readonly now: () => number;
  private readonly activeRuns = new Set<ActiveHelperRun>();
  private readonly runAdmission = new AppSandboxRunAdmission();
  private closed = false;

  constructor(options: NativeAppSandboxTaskExecutorOptions) {
    validateOptions(options);
    this.helperPath = options.helperPath;
    this.containerRoot = options.containerRoot;
    this.expectedHelperContentSha256 = options.expectedHelperContentSha256;
    this.releaseMode = options.releaseMode;
    if (options.releaseMode === "production") {
      if (options.productionReleaseEvidence === undefined || options.productionReleaseSignature === undefined ||
          options.expectedHelperContentSha256 === undefined) {
        throw new Error("Production App Sandbox tasks require Developer ID release evidence");
      }
      const expectation: AppSandboxHelperReleaseExpectation = {
        helperPath: options.helperPath,
        helperContentSha256: options.expectedHelperContentSha256,
        signature: options.productionReleaseSignature
      };
      validateAppSandboxHelperReleaseEvidence(options.productionReleaseEvidence, expectation);
      this.productionReleaseEvidence = options.productionReleaseEvidence;
    }
    this.attestationKeyId = options.attestationKeyId;
    this.attestationPublicKey = exportRawEd25519PublicKey(options.attestationPublicKey);
    this.attestationVerifier = options.attestationVerifier;
    this.networkEvidenceAccepted = options.networkEvidenceAccepted === true;
    this.now = options.now ?? Date.now;
    this.configuredAvailable = process.platform === "darwin" &&
      options.enabled === true &&
      options.hostEvidenceAccepted === true &&
      options.expectedHelperContentSha256 !== undefined &&
      options.releaseMode !== undefined &&
      (options.releaseMode === "development-probe" || this.productionReleaseEvidence !== undefined);
    this.capabilityBase = Object.freeze({
      schemaVersion: "0.1",
      mechanism: "darwin-app-sandbox-helper-v1",
      available: this.configuredAvailable,
      descriptorHandoff: this.configuredAvailable ? "verified" : "unproven",
      helperAuthentication: this.configuredAvailable ? "native-peer-and-hmac" : "unproven",
      helperContentIdentity: this.configuredAvailable ? "verified" : "unproven",
      helperReleaseMode: this.configuredAvailable && this.releaseMode !== undefined ? this.releaseMode : "unproven",
      productionRelease: this.configuredAvailable && this.productionReleaseEvidence !== undefined ? "developer-id-notarized" : "unproven",
      attestationVerification: this.configuredAvailable ? "native-ed25519" : "unproven",
      fixedInterpreter: this.configuredAvailable ? "/bin/sh" : "unproven",
      scriptDescriptor: this.configuredAvailable ? "verified" : "unproven",
      containerCwd: this.configuredAvailable ? "verified" : "unproven",
      networkProxy: this.configuredAvailable && this.networkEvidenceAccepted ? "broker-loopback-allowlist-v1" : "unproven",
      ...(options.evidenceRef === undefined ? {} : { evidenceRef: options.evidenceRef })
    });
  }

  get available(): boolean {
    return this.configuredAvailable && !this.runAdmission.isPoisoned;
  }

  get publicEnablement(): TaskRunnerPublicEnablement {
    if (!this.available) return "unavailable";
    return this.productionReleaseEvidence === undefined ? "staging-only" : "production";
  }

  get capability(): AppSandboxTaskExecutorCapability {
    return Object.freeze({ ...this.capabilityBase, available: this.available });
  }

  async run(
    request: AppSandboxTaskExecutionRequest,
    control: Pick<import("./task-runner.js").TaskExecutionControl, "timeoutMs" | "shouldCancel" | "onProcessStarted" | "onProcessOwnershipChanged">
  ): Promise<ProcessExecutionResult> {
    if (this.closed || !this.available) {
      throw new BrokerError("POLICY_DENIED", "App Sandbox task execution is not enabled");
    }
    const safe = validateRequest(request, control.timeoutMs, this.attestationKeyId, this.attestationVerifier);
    if (safe.networkPolicy === "allowlist" && !this.networkEvidenceAccepted) {
      throw new BrokerError("POLICY_DENIED", "App Sandbox network evidence is not accepted");
    }
    if (control.shouldCancel()) throw new BrokerError("CANCELLED", "App Sandbox task was cancelled before launch");
    const cwdPath = getDescriptorPath(safe.cwdFd);
    if (getDescriptorPath(safe.executableFd) !== "/bin/sh") {
      throw new BrokerError("POLICY_DENIED", "App Sandbox task executable must be the fixed /bin/sh interpreter");
    }
    const finishRun = this.runAdmission.begin();
    let requestKey: Buffer | undefined;
    let runDirectory: string | undefined;
    let child: ChildProcess | undefined;
    let socket: Socket | undefined;
    let controlDescriptors: HelperControlDescriptors | undefined;
    let filesystemStage: AppSandboxFilesystemStage | undefined;
    let networkBrokerSocket: NodeSocket | undefined;
    let networkHelperDescriptor: number | undefined;
    let networkChannel: BrokerNetworkProxyChannel | undefined;
    let settled = false;
    let processBoundaryVerified = true;
    try {
      const runKey = randomBytes(32);
      requestKey = runKey;
      const helperPathIdentity = await captureProcessPathIdentity(this.helperPath, "executable");
      if (helperPathIdentity.contentSha256 !== this.expectedHelperContentSha256) {
        throw new BrokerError("POLICY_DENIED", "App Sandbox helper content identity does not match host evidence");
      }
      if (this.releaseMode === "production") {
        await assertProductionHelperBundleStable(this.helperPath, this.productionReleaseEvidence!);
      }
      const taskRunDirectory = await createRunDirectory(this.containerRoot);
      runDirectory = taskRunDirectory;
      filesystemStage = await stageAppSandboxFilesystem({
        filesystemRoots: safe.filesystemRoots,
        cwdPath,
        runDirectory: taskRunDirectory
      });
      controlDescriptors = await writeHelperKeyDescriptors(requestKey, this.attestationKeyId, this.attestationPublicKey, this.now());
      const socketPath = join(taskRunDirectory, "h.sock");
      const snapshotRoot = join(taskRunDirectory, "S");
      await mkdir(snapshotRoot, { recursive: false, mode: 0o700 });
      const networkEnabled = safe.networkPolicy === "allowlist";
      const networkChannelToken = networkEnabled ? randomBytes(32).toString("hex") : undefined;
      if (networkEnabled) {
        const [brokerDescriptor, helperDescriptor] = createDescriptorHandoffSocketPair();
        networkBrokerSocket = new Socket({ fd: brokerDescriptor, readable: true, writable: true });
        networkHelperDescriptor = helperDescriptor;
        const networkPolicy = createBrokerNetworkProxyPolicy({
          policyId: `app-sandbox:${safe.signedAttestation.payload.snapshotRef}`,
          destinations: safe.networkAllowlist,
          maxRequestBytes: 32 * 1024,
          maxResponseBytes: Math.min(256 * 1024, safe.outputCapBytes),
          timeoutMs: Math.min(safe.timeoutMs, 60_000)
        });
        networkChannel = new BrokerNetworkProxyChannel({
          socket: networkBrokerSocket,
          proxy: new BrokerNetworkProxy({ enabled: true, policy: networkPolicy }),
          capabilityToken: networkChannelToken!,
          shouldCancel: control.shouldCancel
        });
        networkChannel.start();
      }
      const unsigned = createUnsignedEnvelope(safe, this.now(), networkChannelToken);
      const signed: AppSandboxSignedEnvelope = {
        ...unsigned,
        authenticationProof: hmacProof(APP_SANDBOX_REQUEST_DOMAIN, sha256(canonicalJson(unsigned)), runKey)
      };
      child = spawn(this.helperPath, [
        networkEnabled ? "--app-sandbox-execute-network-fds" : "--app-sandbox-execute-fds",
        socketPath,
        "3",
        "4",
        "5",
        "6",
        snapshotRoot
      ], {
        cwd: this.containerRoot,
        env: { LANG: "C", PATH: "/usr/bin:/bin" },
        shell: false,
        stdio: [
          "ignore", "pipe", "pipe",
          controlDescriptors.requestConfigFd,
          controlDescriptors.attestationConfigFd,
          controlDescriptors.requestKeyFd,
          controlDescriptors.attestationKeyFd
        ]
      });
      processBoundaryVerified = false;
      const active: ActiveHelperRun = { child, cancel: () => child?.kill("SIGTERM") };
      this.activeRuns.add(active);
      await assertProcessPathIdentityStable(this.helperPath, helperPathIdentity, "executable");
      const helperStderr = collectBoundedOutput(child.stderr, MAX_HELPER_STDERR_BYTES);
      const helperStdout = collectBoundedOutput(child.stdout, MAX_HELPER_STDERR_BYTES);
      socket = await connectWithRetry(socketPath, child, helperStderr.read, MAX_HELPER_STARTUP_MS);
      const descriptor = (socket as SocketWithHandle)._handle?.fd;
      if (!Number.isSafeInteger(descriptor) || (descriptor as number) < 0) {
        throw new BrokerError("EXECUTION_FAILED", "App Sandbox helper socket descriptor is unavailable");
      }
      const socketDescriptor = descriptor as number;
      const peer = parsePeerCredentials(loadNativePeerAdapter().getPeerCredentials(socketDescriptor));
      const helperIdentity = captureChildIdentity(child, this.attestationVerifier);
      authorizePeerCredentials(peer, {
        expectedUid: process.getuid?.() ?? peer.uid,
        expectedGid: process.getgid?.() ?? peer.gid,
        allowedProcessIdentity: helperIdentity
      }, (pid) => loadNativePeerAdapter().getProcessIdentity(pid));
      sendDescriptorHandoff(socketDescriptor, Buffer.from(canonicalJson(signed), "utf8"), [
        safe.executableFd,
        filesystemStage.stagedCwdHandle.fd,
        safe.scriptFd!,
        ...(networkHelperDescriptor === undefined ? [] : [networkHelperDescriptor])
      ]);
      if (networkHelperDescriptor !== undefined) {
        loadNativePeerAdapter().closeUnixDescriptor(networkHelperDescriptor);
        networkHelperDescriptor = undefined;
      }
      const result = await readHelperResponse(socket, unsigned, runKey, control, (event) => {
        control.onProcessStarted?.(event.snapshot);
      });
      socket.destroy();
      const exitCode = await waitForChild(child);
      if (exitCode !== 0) {
        throw new BrokerError("UNKNOWN_OUTCOME", `App Sandbox helper exited unexpectedly: ${helperStderr.read()}`, true);
      }
      void helperStdout;
      processBoundaryVerified = result.resultClass !== "UNKNOWN_OUTCOME";
      settled = true;
      return result;
    } catch (error) {
      if (child !== undefined) processBoundaryVerified = false;
      if (error instanceof BrokerError) throw error;
      const detail = error instanceof Error ? error.message.slice(0, 256) : "native transport failure";
      throw new BrokerError("UNKNOWN_OUTCOME", `App Sandbox task outcome could not be established: ${detail}`, true);
    } finally {
      if (socket !== undefined && !socket.destroyed) socket.destroy();
      networkChannel?.close();
      networkBrokerSocket?.destroy();
      if (networkHelperDescriptor !== undefined) {
        try { loadNativePeerAdapter().closeUnixDescriptor(networkHelperDescriptor); } catch { /* best-effort cleanup */ }
      }
      if (child !== undefined) {
        const active = [...this.activeRuns].find((entry) => entry.child === child);
        if (!settled && active !== undefined) await terminateChild(active);
        if (active !== undefined) this.activeRuns.delete(active);
      }
      requestKey?.fill(0);
      await closeHelperControlDescriptors(controlDescriptors);
      await filesystemStage?.stagedCwdHandle.close().catch(() => undefined);
      if (runDirectory !== undefined) await rm(runDirectory, { recursive: true, force: true }).catch(() => undefined);
      finishRun(processBoundaryVerified);
    }
  }

  async close(): Promise<void> {
    if (this.closed) return;
    this.closed = true;
    const activeRuns = [...this.activeRuns];
    for (const active of activeRuns) active.cancel();
    await Promise.all(activeRuns.map((active) => waitForChild(active.child).catch(() => undefined)));
    this.attestationPublicKey.fill(0);
  }
}

async function terminateChild(active: ActiveHelperRun): Promise<void> {
  if (active.child.exitCode !== null) return;
  active.cancel();
  const exited = await Promise.race([
    waitForChild(active.child).then(() => true),
    delay(500).then(() => false)
  ]);
  if (!exited && active.child.exitCode === null) {
    active.child.kill("SIGKILL");
    await waitForChild(active.child).catch(() => undefined);
  }
}

async function assertProductionHelperBundleStable(helperPath: string, evidence: AppSandboxHelperReleaseEvidence): Promise<void> {
  const ownerUid = process.getuid?.();
  if (ownerUid === undefined) {
    throw new BrokerError("POLICY_DENIED", "Production App Sandbox helper ownership cannot be established");
  }
  const bundlePath = appSandboxHelperBundlePath(helperPath);
  if (bundlePath !== evidence.artifact.artifactPath) {
    throw new BrokerError("POLICY_DENIED", "Production App Sandbox helper release path is not identity-bound");
  }
  let current;
  try {
    current = await readMacOsReleaseArtifactSummary(bundlePath, ownerUid);
  } catch {
    throw new BrokerError("POLICY_DENIED", "Production App Sandbox helper release artifact is unavailable");
  }
  if (current.sha256 !== evidence.artifact.sha256 || current.bytes !== evidence.artifact.bytes ||
      current.files !== evidence.artifact.files || current.directories !== evidence.artifact.directories ||
      current.device !== evidence.artifact.device || current.inode !== evidence.artifact.inode ||
      current.mode !== evidence.artifact.mode) {
    throw new BrokerError("POLICY_DENIED", "Production App Sandbox helper release artifact changed");
  }
}

function validateOptions(options: NativeAppSandboxTaskExecutorOptions): void {
  if (options === null || typeof options !== "object" ||
      typeof options.helperPath !== "string" || !isCanonicalAbsolutePath(options.helperPath) ||
      typeof options.containerRoot !== "string" || !isCanonicalAbsolutePath(options.containerRoot) ||
      typeof options.attestationKeyId !== "string" || !KEY_ID_PATTERN.test(options.attestationKeyId) ||
      (options.evidenceRef !== undefined && !/^[A-Za-z0-9._:/-]{1,256}$/u.test(options.evidenceRef)) ||
      (options.enabled !== undefined && typeof options.enabled !== "boolean") ||
      (options.hostEvidenceAccepted !== undefined && typeof options.hostEvidenceAccepted !== "boolean") ||
      (options.networkEvidenceAccepted !== undefined && typeof options.networkEvidenceAccepted !== "boolean") ||
      (options.releaseMode !== undefined && options.releaseMode !== "development-probe" && options.releaseMode !== "production") ||
      (options.expectedHelperContentSha256 !== undefined && !DIGEST_PATTERN.test(options.expectedHelperContentSha256))) {
    throw new Error("App Sandbox task executor options are invalid");
  }
}

function validateRequest(
  request: AppSandboxTaskExecutionRequest,
  controlTimeoutMs: number,
  expectedKeyId: string,
  verifier: NativeAppSandboxTaskExecutorOptions["attestationVerifier"]
): AppSandboxTaskExecutionRequest {
  if (request === null || typeof request !== "object" || request.schemaVersion !== "0.1" ||
      request.executionKind !== "posix-sh-script" || !Number.isSafeInteger(request.executableFd) || request.executableFd < 0 ||
      !Number.isSafeInteger(request.cwdFd) || request.cwdFd < 0 || !Number.isSafeInteger(request.scriptFd) || (request.scriptFd ?? -1) < 0 ||
      typeof request.scriptContentSha256 !== "string" || !DIGEST_PATTERN.test(request.scriptContentSha256) ||
      !Array.isArray(request.filesystemRoots) || request.filesystemRoots.length < 1 || request.filesystemRoots.length > 32 ||
      request.filesystemRoots.some((root) => typeof root !== "string" || !isCanonicalAbsolutePath(root)) ||
      !Array.isArray(request.args) || request.args.some((arg) => typeof arg !== "string" || arg.includes("\0") || arg.includes("\n") || isAbsolute(arg)) ||
      request.args.length > 128 || !isPlainDataRecord(request.environment) || Object.keys(request.environment).length > 64 ||
      Object.values(request.environment).some((value) => typeof value !== "string" || value.includes("\0") || value.includes("\n")) ||
      (request.networkPolicy !== "none" && request.networkPolicy !== "allowlist") ||
      !Array.isArray(request.networkAllowlist) || request.networkAllowlist.length > 32 ||
      request.networkAllowlist.some((destination) => typeof destination !== "string" || parseTaskNetworkDestination(destination) === null) ||
      !Number.isSafeInteger(request.timeoutMs) || request.timeoutMs < 25 || request.timeoutMs > MAX_TIMEOUT_MS ||
      !Number.isSafeInteger(controlTimeoutMs) || controlTimeoutMs < 25 || controlTimeoutMs > request.timeoutMs ||
      !Number.isSafeInteger(request.outputCapBytes) || request.outputCapBytes < 1 || request.outputCapBytes > 2 * 1024 * 1024 ||
      request.signedAttestation.keyId !== expectedKeyId) {
    throw new BrokerError("PRECONDITION_FAILED", "App Sandbox task execution request is malformed");
  }
  if (verifier !== undefined) verifier.verify(request.signedAttestation);
  if (request.signedAttestation.payload.audience !== APP_SANDBOX_AUDIENCE ||
      request.signedAttestation.payload.processTreePolicy !== "single_process" ||
      request.signedAttestation.payload.credentialPolicy !== "none" ||
      request.signedAttestation.payload.networkPolicy !== request.networkPolicy) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox task attestation policy is not supported");
  }
  if ((request.networkPolicy === "none" && request.networkAllowlist.length !== 0) ||
      (request.networkPolicy === "allowlist" && request.networkAllowlist.length === 0) ||
      new Set(request.networkAllowlist).size !== request.networkAllowlist.length) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox network policy and allowlist do not match");
  }
  if (sha256(canonicalJson(request.filesystemRoots)) !== request.signedAttestation.payload.filesystemRootsDigest) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox filesystem roots are not bound to the attestation");
  }
  return request;
}

function createUnsignedEnvelope(request: AppSandboxTaskExecutionRequest, nowMs: number, networkChannelToken?: string): AppSandboxUnsignedEnvelope {
  if (!Number.isSafeInteger(nowMs) || nowMs < 0) throw new BrokerError("PRECONDITION_FAILED", "App Sandbox task clock is invalid");
  if ((request.networkPolicy === "allowlist" && (typeof networkChannelToken !== "string" || !/^[a-f0-9]{64}$/u.test(networkChannelToken))) ||
      (request.networkPolicy === "none" && networkChannelToken !== undefined)) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox network channel binding is invalid");
  }
  const expiresAtMs = Math.min(request.signedAttestation.expiresAtMs, nowMs + Math.min(request.timeoutMs, 30_000));
  if (expiresAtMs <= nowMs) throw new BrokerError("AUTH_EXPIRED", "App Sandbox task attestation has expired");
  return {
    schemaVersion: APP_SANDBOX_SCHEMA_VERSION,
    mechanism: APP_SANDBOX_MECHANISM,
    requestId: `snapshot-request:app-sandbox-${randomBytes(24).toString("hex")}`,
    timestampMs: nowMs,
    expiresAtMs,
    signedAttestation: request.signedAttestation,
    executionKind: "posix-sh-script",
    scriptContentSha256: request.scriptContentSha256!,
    args: [...request.args],
    environment: { ...request.environment },
    timeoutMs: request.timeoutMs,
    outputCapBytes: request.outputCapBytes,
    ...(networkChannelToken === undefined ? {} : { networkChannelToken })
  };
}

interface HelperControlDescriptors {
  requestConfigFd: number;
  attestationConfigFd: number;
  requestKeyFd: number;
  attestationKeyFd: number;
  handles: readonly FileHandle[];
}

async function writeHelperKeyDescriptors(
  requestKey: Buffer,
  keyId: string,
  publicKey: Buffer,
  nowMs: number
): Promise<HelperControlDescriptors> {
  const expiresAtMs = nowMs + 60_000;
  const requestConfig = Buffer.from(`${canonicalJson({
    schemaVersion: "0.1",
    revision: 1,
    keys: [{ keySource: "descriptor", path: "fd:request-key", keyDigest: sha256(requestKey), notBeforeMs: nowMs - 1_000, expiresAtMs }]
  })}\n`, "utf8");
  const attestationConfig = Buffer.from(`${canonicalJson({
    schemaVersion: "0.1",
    revision: 1,
    keys: [{ keyId, path: "fd:attestation-key", publicKeyDigest: sha256(publicKey), notBeforeMs: nowMs - 1_000, expiresAtMs }]
  })}\n`, "utf8");
  const tempDirectory = await mkdtemp(join(tmpdir(), "mop-app-sandbox-control-"));
  const handles: FileHandle[] = [];
  try {
    for (const bytes of [requestConfig, attestationConfig, requestKey, publicKey]) {
      const handle = await createUnlinkedProtectedDescriptor(tempDirectory, bytes);
      handles.push(handle);
    }
    await rm(tempDirectory, { recursive: true, force: true });
    return {
      requestConfigFd: handles[0]!.fd,
      attestationConfigFd: handles[1]!.fd,
      requestKeyFd: handles[2]!.fd,
      attestationKeyFd: handles[3]!.fd,
      handles
    };
  } catch (error) {
    await Promise.all(handles.map((handle) => handle.close().catch(() => undefined)));
    await rm(tempDirectory, { recursive: true, force: true }).catch(() => undefined);
    throw error;
  }
}

async function createUnlinkedProtectedDescriptor(tempDirectory: string, bytes: Buffer): Promise<FileHandle> {
  const path = join(tempDirectory, randomBytes(12).toString("hex"));
  const handle = await open(path, constants.O_CREAT | constants.O_EXCL | constants.O_RDWR, 0o600);
  try {
    const written = await handle.write(bytes, 0, bytes.byteLength, 0);
    if (written.bytesWritten !== bytes.byteLength) throw new Error("Protected helper descriptor write was partial");
    await handle.sync();
    await rm(path, { force: true });
    return handle;
  } catch (error) {
    await handle.close().catch(() => undefined);
    await rm(path, { force: true }).catch(() => undefined);
    throw error;
  }
}

async function closeHelperControlDescriptors(descriptors: HelperControlDescriptors | undefined): Promise<void> {
  if (descriptors === undefined) return;
  await Promise.all(descriptors.handles.map((handle) => handle.close().catch(() => undefined)));
}

async function createRunDirectory(containerRoot: string): Promise<string> {
  await assertProtectedDirectory(containerRoot);
  const runDirectory = join(containerRoot, "R", randomBytes(6).toString("hex"));
  await mkdir(dirname(runDirectory), { recursive: true, mode: 0o700 });
  await mkdir(runDirectory, { recursive: false, mode: 0o700 });
  const canonical = await realpath(runDirectory);
  if (canonical !== runDirectory || !isPathWithin(containerRoot, canonical)) {
    await rm(runDirectory, { recursive: true, force: true }).catch(() => undefined);
    throw new BrokerError("POLICY_DENIED", "App Sandbox run directory escaped its container root");
  }
  return canonical;
}

async function assertProtectedDirectory(path: string): Promise<void> {
  const canonical = await realpath(path).catch(() => { throw new BrokerError("POLICY_DENIED", "App Sandbox container root is unavailable"); });
  if (canonical !== path) throw new BrokerError("POLICY_DENIED", "App Sandbox container root is not canonical");
  const stat = lstatSync(path);
  const uid = process.getuid?.();
  if (!stat.isDirectory() || stat.isSymbolicLink() || (uid !== undefined && stat.uid !== uid) || (stat.mode & 0o022) !== 0) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox container root is not protected");
  }
}

async function connectWithRetry(path: string, child: ChildProcess, readStderr: () => string, timeoutMs: number): Promise<Socket> {
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown;
  while (Date.now() < deadline) {
    if (child.exitCode !== null) throw new BrokerError("EXECUTION_FAILED", `App Sandbox helper exited before connect: ${readStderr()}`);
    try {
      return await new Promise<Socket>((resolvePromise, rejectPromise) => {
        const socket = connect(path);
        const onError = (error: unknown): void => { socket.destroy(); rejectPromise(error); };
        socket.once("error", onError);
        socket.once("connect", () => {
          socket.removeListener("error", onError);
          resolvePromise(socket);
        });
      });
    } catch (error) {
      lastError = error;
      const code = (error as NodeJS.ErrnoException)?.code;
      if (code !== "ENOENT" && code !== "ECONNREFUSED") {
        let kind = "missing";
        try { kind = lstatSync(path).isSocket() ? "socket" : lstatSync(path).isDirectory() ? "directory" : "regular"; } catch { /* preserve the transport error */ }
        throw new Error(`${error instanceof Error ? error.message : String(error)}; path_kind=${kind}; helper_exit=${child.exitCode ?? "running"}; helper_stderr=${readStderr()}`);
      }
      await delay(10);
    }
  }
  throw new BrokerError("TIMEOUT", `App Sandbox helper socket did not become available: ${String(lastError ?? "timeout")}`, true);
}

async function readHelperResponse(
  socket: Socket,
  request: AppSandboxUnsignedEnvelope,
  key: Buffer,
  control: Pick<import("./task-runner.js").TaskExecutionControl, "timeoutMs" | "shouldCancel" | "onProcessStarted" | "onProcessOwnershipChanged">,
  onEvent: (event: AppSandboxProcessEvent) => void
): Promise<ProcessExecutionResult> {
  return new Promise<ProcessExecutionResult>((resolvePromise, rejectPromise) => {
    let settled = false;
    let pending = Buffer.alloc(0);
    let totalBytes = 0;
    const cancelTimer = setInterval(() => {
      if (control.shouldCancel()) socket.destroy();
    }, 25);
    cancelTimer.unref?.();
    const fail = (error: unknown): void => {
      if (settled) return;
      settled = true;
      clearInterval(cancelTimer);
      rejectPromise(error instanceof BrokerError ? error : new BrokerError("UNKNOWN_OUTCOME", "App Sandbox helper response failed", true));
    };
    socket.setTimeout(control.timeoutMs, () => fail(new BrokerError("TIMEOUT", "App Sandbox task transport timed out", true)));
    socket.once("error", () => fail(new BrokerError("UNKNOWN_OUTCOME", "App Sandbox task socket failed", true)));
    socket.on("data", (chunk: Buffer) => {
      if (settled) return;
      totalBytes += chunk.byteLength;
      if (totalBytes > MAX_RESPONSE_BYTES) {
        fail(new BrokerError("OUTPUT_LIMIT", "App Sandbox helper response exceeded the byte limit"));
        return;
      }
      pending = Buffer.concat([pending, chunk]);
      for (;;) {
        const newline = pending.indexOf(0x0a);
        if (newline < 0) return;
        const line = pending.subarray(0, newline);
        pending = pending.subarray(newline + 1);
        if (line.byteLength === 0) {
          fail(new BrokerError("AUTH_INVALID", "App Sandbox helper response contained an empty frame"));
          return;
        }
        try {
          const raw = parseJsonUtf8Strict(line);
          if (isPlainDataRecord(raw) && raw.kind === "process_started") {
            const event = authenticateProcessEvent(raw, request, key);
            onEvent(event);
            continue;
          }
          if (pending.some((byte) => !isAsciiWhitespace(byte))) {
            fail(new BrokerError("AUTH_INVALID", "App Sandbox helper response contained trailing bytes"));
            return;
          }
          settled = true;
          clearInterval(cancelTimer);
          resolvePromise(authenticateResponse(raw, request, key));
          return;
        } catch (error) {
          fail(error);
          return;
        }
      }
    });
    socket.once("close", () => {
      if (!settled) fail(new BrokerError("UNKNOWN_OUTCOME", "App Sandbox helper closed without an authenticated response", true));
    });
  });
}

function authenticateProcessEvent(raw: Record<string, unknown>, request: AppSandboxUnsignedEnvelope, key: Buffer): AppSandboxProcessEvent {
  if (Object.keys(raw).sort().join(",") !== "eventProof,kind,requestId,snapshot" ||
      raw.kind !== "process_started" || raw.requestId !== request.requestId || typeof raw.eventProof !== "string") {
    throw new BrokerError("AUTH_INVALID", "App Sandbox process event identity is invalid");
  }
  const body = { kind: raw.kind, requestId: raw.requestId, snapshot: raw.snapshot };
  if (!safeEqualHex(raw.eventProof, hmacProof(APP_SANDBOX_RESPONSE_DOMAIN, sha256(canonicalJson(request)) + canonicalJson(body), key))) {
    throw new BrokerError("AUTH_INVALID", "App Sandbox process event authentication failed");
  }
  const snapshot = validateRootHelperSnapshotProcessOwnershipSnapshot(raw.snapshot);
  return { kind: "process_started", requestId: request.requestId, snapshot, eventProof: raw.eventProof };
}

function authenticateResponse(raw: unknown, request: AppSandboxUnsignedEnvelope, key: Buffer): ProcessExecutionResult {
  if (!isPlainDataRecord(raw) || typeof raw.requestId !== "string" || raw.requestId !== request.requestId || typeof raw.responseProof !== "string") {
    throw new BrokerError("AUTH_INVALID", "App Sandbox response identity is invalid");
  }
  const body = { ...raw };
  delete body.responseProof;
  if (!safeEqualHex(raw.responseProof, hmacProof(APP_SANDBOX_RESPONSE_DOMAIN, sha256(canonicalJson(request)) + canonicalJson(body), key))) {
    throw new BrokerError("AUTH_INVALID", "App Sandbox response authentication failed");
  }
  if (raw.ok === true && isPlainDataRecord(raw.result)) return validateRootHelperSnapshotProcessResult(raw.result);
  if (raw.ok === false && typeof raw.resultClass === "string" && isPlainDataRecord(raw.error) &&
      typeof raw.error.message === "string" && typeof raw.error.retryable === "boolean") {
    throw new BrokerError(raw.resultClass as BrokerError["errorClass"], raw.error.message, raw.error.retryable);
  }
  throw new BrokerError("EXECUTION_FAILED", "App Sandbox response is malformed");
}

function hmacProof(domain: string, digest: string, key: Buffer): string {
  return createHmac("sha256", key).update(domain, "utf8").update(digest, "utf8").digest("hex");
}

function safeEqualHex(left: unknown, right: string): boolean {
  if (typeof left !== "string" || !/^[a-f0-9]{64}$/u.test(left) || !/^[a-f0-9]{64}$/u.test(right)) return false;
  return timingSafeEqual(Buffer.from(left, "hex"), Buffer.from(right, "hex"));
}

function captureChildIdentity(child: ChildProcess, verifier: NativeAppSandboxTaskExecutorOptions["attestationVerifier"]): PeerProcessIdentity {
  if (!Number.isSafeInteger(child.pid) || child.pid === undefined || child.pid < 1) {
    throw new BrokerError("EXECUTION_FAILED", "App Sandbox helper process identity is unavailable");
  }
  const native = loadNativePeerAdapter();
  const identity = native.getProcessIdentity(child.pid);
  if (verifier !== undefined && identity === undefined) throw new BrokerError("POLICY_DENIED", "App Sandbox helper process identity is unavailable");
  const record = identity as Record<string, unknown>;
  if (record === null || typeof record !== "object" || !Number.isSafeInteger(record.pid) ||
      !Number.isSafeInteger(record.startTimeMicros) || record.pid !== child.pid || (record.startTimeMicros as number) < 1) {
    throw new BrokerError("POLICY_DENIED", "App Sandbox helper process identity is malformed");
  }
  return { pid: child.pid, startTimeMicros: record.startTimeMicros as number };
}

function waitForChild(child: ChildProcess): Promise<number> {
  return new Promise<number>((resolvePromise, rejectPromise) => {
    if (child.exitCode !== null) {
      resolvePromise(child.exitCode);
      return;
    }
    child.once("error", rejectPromise);
    child.once("exit", (code) => resolvePromise(code ?? -1));
  });
}

function collectBoundedOutput(stream: NodeJS.ReadableStream | null, cap: number): { read: () => string } {
  let bytes = 0;
  let value = "";
  stream?.on("data", (chunk: Buffer | string) => {
    if (bytes >= cap) return;
    const text = Buffer.isBuffer(chunk) ? chunk.toString("utf8") : String(chunk);
    const remaining = cap - bytes;
    value += text.slice(0, remaining);
    bytes += Buffer.byteLength(text.slice(0, remaining), "utf8");
  });
  return { read: () => value };
}

function exportRawEd25519PublicKey(value: Buffer | string | KeyObject): Buffer {
  if (Buffer.isBuffer(value)) {
    if (value.byteLength !== 32) throw new Error("App Sandbox attestation public key must contain 32 bytes");
    return Buffer.from(value);
  }
  const key = value instanceof Object && "type" in value ? value as KeyObject : createPublicKey(value);
  if (key.asymmetricKeyType !== "ed25519") throw new Error("App Sandbox attestation public key must be Ed25519");
  const der = key.export({ format: "der", type: "spki" });
  if (!Buffer.isBuffer(der) || der.byteLength < 32) throw new Error("App Sandbox attestation public key is malformed");
  return Buffer.from(der.subarray(-32));
}

function isCanonicalAbsolutePath(value: string): boolean {
  return isAbsolute(value) && resolve(value) === value && !value.includes("\0") && !value.includes("\n");
}

function isPathWithin(root: string, target: string): boolean {
  const suffix = relative(root, target);
  return suffix === "" || (suffix !== ".." && !suffix.startsWith(`..${requirePathSeparator()}`) && !isAbsolute(suffix));
}

function requirePathSeparator(): string {
  return "/";
}

function isPlainDataRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function isAsciiWhitespace(value: number): boolean {
  return value === 0x09 || value === 0x0a || value === 0x0c || value === 0x0d || value === 0x20;
}
