import { isAbsolute, resolve } from "node:path";
import { BrokerError } from "@mac-operator/contracts";
import { loadPrivilegedHelperKeyConfigWithoutBroker } from "./privileged-helper-keyring.js";
import {
  RootHelperSnapshotAuthorityClient,
  type RootHelperSnapshotAuthorityPoller
} from "./root-helper-snapshot-authority.js";
import {
  RootHelperSnapshotServer,
  type RootHelperSnapshotSandboxPolicy,
  type RootHelperSnapshotServerOptions
} from "./root-helper-snapshot-transport.js";
import type { DescriptorSnapshotAttestationVerifier } from "./descriptor-snapshot-attestation.js";
import type { NativePeerPolicy } from "./native-peer-ipc-server.js";
import type { CodeSignatureExpectation } from "./macos-install-plan.js";
import type { RootHelperSnapshotReleaseEvidence } from "./root-helper-snapshot-release.js";
import { assertRootHelperSnapshotReleaseArtifactStable } from "./root-helper-snapshot-release.js";
import {
  MemoryRootHelperSnapshotStatusReplayGuard,
  RootHelperSnapshotStatusIpcServer,
  type RootHelperSnapshotStatusReadback
} from "./root-helper-snapshot-status-ipc.js";

export type RootHelperSnapshotRuntimeState = "stopped" | "starting" | "running" | "stopping" | "failed";

export type RootHelperSnapshotRuntimeStartupErrorCode =
  | "KEY_CONFIG_UNAVAILABLE"
  | "SOCKET_INVALID"
  | "PEER_POLICY_INVALID"
  | "AUTHORITY_UNAVAILABLE"
  | "SANDBOX_UNAVAILABLE"
  | "ATTESTATION_VERIFICATION_UNAVAILABLE"
  | "KEY_EXPIRED"
  | "SERVER_UNAVAILABLE";

export class RootHelperSnapshotRuntimeStartupError extends Error {
  readonly code: RootHelperSnapshotRuntimeStartupErrorCode;

  constructor(code: RootHelperSnapshotRuntimeStartupErrorCode, message: string) {
    super(message);
    this.name = "RootHelperSnapshotRuntimeStartupError";
    this.code = code;
  }
}

export interface RootHelperSnapshotRuntimeKeyMaterialOptions {
  /** Root-owned protected key configuration; callers cannot provide raw key bytes. */
  helperKeyConfigPath: string;
  /** Required only when the protected key source is Keychain-backed. */
  keychainTrustedExecutablePath?: string;
  socketPath: string;
  /** Optional separately authenticated read-only status socket. */
  statusSocketPath?: string;
  /** Metadata projected by the status socket; no secret material is included. */
  statusMetadata?: Pick<RootHelperSnapshotStatusReadback, "sourceRevision" | "contractVersion" | "evidenceRef">;
  /** The helper snapshot endpoint must never reuse the Broker IPC socket. */
  brokerSocketPath: string;
  /** Broker-owned authority polling socket; required for an available helper. */
  authoritySocketPath?: string;
  reservedSocketPaths?: readonly string[];
  /** The Broker peer must be a named non-root process identity. */
  peerPolicy: NativePeerPolicy;
  verifier: DescriptorSnapshotAttestationVerifier;
  snapshotRoot: string;
  sandboxPolicies: ReadonlyMap<string, RootHelperSnapshotSandboxPolicy>;
  enabled?: boolean;
  hostEvidenceAccepted?: boolean;
  sandboxIsolationAccepted?: boolean;
  sandboxEvidenceRef?: string;
  attestationVerificationAccepted?: boolean;
  attestationEvidenceRef?: string;
  evidenceRef?: string;
  /** Explicit release provenance mode for the exact native root-helper executable. */
  releaseMode?: "development-probe" | "production";
  /** Required with production mode; generated by the read-only release preflight. */
  productionReleaseEvidence?: RootHelperSnapshotReleaseEvidence;
  /** Required with production mode; pins the Developer ID identity. */
  productionReleaseSignature?: CodeSignatureExpectation;
  /** Required with production mode; exact native helper executable path. */
  productionReleaseArtifactPath?: string;
  now?: () => number;
  pollIntervalMs?: number;
  authorityPollIntervalMs?: number;
  protectedFilesystemRoots?: readonly string[];
}

/**
 * Owns the separately authenticated root-helper snapshot listener lifecycle.
 * This runtime is intentionally not a Broker channel and is never registered
 * with MCP. The server remains unavailable until root ownership and independent
 * host evidence are both present.
 */
export class RootHelperSnapshotRuntime {
  private stateValue: RootHelperSnapshotRuntimeState = "stopped";
  private operation: Promise<void> = Promise.resolve();

  constructor(
    private readonly server: RootHelperSnapshotServer,
    private readonly statusServer?: RootHelperSnapshotStatusIpcServer,
    private readonly statusStateRef?: { value: RootHelperSnapshotRuntimeState },
    private readonly statusMetadataRef?: { value: Pick<RootHelperSnapshotStatusReadback, "sourceRevision" | "contractVersion" | "evidenceRef"> | undefined }
  ) {}

  get state(): RootHelperSnapshotRuntimeState {
    return this.stateValue;
  }

  get available(): boolean {
    return this.server.available;
  }

  get capability(): RootHelperSnapshotServer["capability"] {
    return this.server.capability;
  }

  /** Binds service-owned status metadata before the root service can start. */
  setStatusMetadata(metadata: Pick<RootHelperSnapshotStatusReadback, "sourceRevision" | "contractVersion" | "evidenceRef">): void {
    if (this.statusMetadataRef === undefined) return;
    if (this.stateValue !== "stopped") {
      throw new RootHelperSnapshotRuntimeStartupError("SERVER_UNAVAILABLE", "Root-helper status metadata cannot change after startup");
    }
    validateStatusMetadata(metadata);
    this.statusMetadataRef.value = { ...metadata };
  }

  start(): Promise<void> {
    return this.enqueue(() => this.startInternal());
  }

  close(): Promise<void> {
    return this.enqueue(() => this.closeInternal());
  }

  private async startInternal(): Promise<void> {
    if (this.stateValue !== "stopped") {
      throw new RootHelperSnapshotRuntimeStartupError("SERVER_UNAVAILABLE", `Root-helper snapshot runtime cannot start from ${this.stateValue}`);
    }
    if (!this.server.available) {
      await this.server.close();
      await this.statusServer?.close();
      throw new BrokerError("POLICY_DENIED", "Root-helper snapshot runtime is unavailable on this host");
    }
    this.stateValue = "starting";
    if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
    try {
      if (this.statusServer !== undefined && this.statusMetadataRef?.value === undefined) {
        throw new RootHelperSnapshotRuntimeStartupError("SERVER_UNAVAILABLE", "Root-helper status metadata is not bound");
      }
      await this.server.listen();
      await this.statusServer?.listen();
      this.stateValue = "running";
      if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
    } catch (error) {
      try {
        await this.statusServer?.close();
        await this.server.close();
        this.stateValue = "stopped";
        if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
      } catch (cleanupError) {
        this.stateValue = "failed";
        if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
        throw new AggregateError([error, cleanupError], "Root-helper snapshot startup failed and cleanup also failed");
      }
      throw error;
    }
  }

  private async closeInternal(): Promise<void> {
    if (this.stateValue === "stopped") {
      await this.statusServer?.close();
      await this.server.close();
      return;
    }
    this.stateValue = "stopping";
    if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
    try {
      await this.statusServer?.close();
      await this.server.close();
      this.stateValue = "stopped";
      if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
    } catch (error) {
      this.stateValue = "failed";
      if (this.statusStateRef) this.statusStateRef.value = this.stateValue;
      throw error;
    }
  }

  private enqueue(operation: () => Promise<void>): Promise<void> {
    const run = this.operation.catch(() => undefined).then(operation);
    this.operation = run;
    return run;
  }
}

/**
 * Assemble the root-domain runtime from protected key material. The factory
 * does not install launchd, change ownership, or enable a public capability.
 */
export async function createRootHelperSnapshotRuntimeFromKeyMaterial(
  options: RootHelperSnapshotRuntimeKeyMaterialOptions
): Promise<RootHelperSnapshotRuntime> {
  validateRuntimeOptions(options);
  if (options.enabled === true && options.hostEvidenceAccepted === true &&
      (options.sandboxIsolationAccepted !== true || options.sandboxEvidenceRef === undefined)) {
    throw new RootHelperSnapshotRuntimeStartupError(
      "SANDBOX_UNAVAILABLE",
      "Enabled root-helper snapshot runtime requires independent supported sandbox evidence"
    );
  }
  if (options.enabled === true && options.hostEvidenceAccepted === true &&
      (options.attestationVerificationAccepted !== true || options.attestationEvidenceRef === undefined)) {
    throw new RootHelperSnapshotRuntimeStartupError(
      "ATTESTATION_VERIFICATION_UNAVAILABLE",
      "Enabled root-helper snapshot runtime requires native Ed25519 attestation verification evidence"
    );
  }
  const now = options.now ?? Date.now;
  if (options.releaseMode === "production") {
    if (options.productionReleaseEvidence === undefined || options.productionReleaseArtifactPath === undefined ||
        options.productionReleaseArtifactPath !== options.productionReleaseEvidence.artifact.artifactPath) {
      throw new RootHelperSnapshotRuntimeStartupError(
        "SERVER_UNAVAILABLE",
        "Production root-helper startup requires identity-bound release evidence"
      );
    }
    try {
      await assertRootHelperSnapshotReleaseArtifactStable(options.productionReleaseEvidence);
    } catch {
      throw new RootHelperSnapshotRuntimeStartupError(
        "SERVER_UNAVAILABLE",
        "Production root-helper release artifact is unavailable or changed"
      );
    }
  }
  let loaded: Awaited<ReturnType<typeof loadPrivilegedHelperKeyConfigWithoutBroker>> | undefined;
  let authorityPoller: RootHelperSnapshotAuthorityPoller | undefined;
  try {
    loaded = await loadPrivilegedHelperKeyConfigWithoutBroker(
      options.helperKeyConfigPath,
      options.keychainTrustedExecutablePath
    );
    const nowMs = now();
    if (!Number.isSafeInteger(nowMs) || nowMs < loaded.key.notBeforeMs || nowMs >= loaded.key.expiresAtMs) {
      throw new RootHelperSnapshotRuntimeStartupError("KEY_EXPIRED", "Root-helper snapshot key is outside its validity window");
    }
    if (options.enabled === true && options.hostEvidenceAccepted === true && options.authoritySocketPath === undefined) {
      throw new RootHelperSnapshotRuntimeStartupError("AUTHORITY_UNAVAILABLE", "Enabled root-helper snapshot runtime requires a Broker authority socket");
    }
    if (options.authoritySocketPath !== undefined) {
      authorityPoller = new RootHelperSnapshotAuthorityClient({
        socketPath: options.authoritySocketPath,
        authenticationKey: loaded.key.key,
        peerPolicy: options.peerPolicy,
        now
      });
    }
    const serverOptions: RootHelperSnapshotServerOptions = {
      socketPath: options.socketPath,
      authenticationKey: loaded.key.key,
      peerPolicy: options.peerPolicy,
      verifier: options.verifier,
      snapshotRoot: options.snapshotRoot,
      sandboxPolicies: options.sandboxPolicies,
      now,
      ...(options.enabled === undefined ? {} : { enabled: options.enabled }),
      ...(options.hostEvidenceAccepted === undefined ? {} : { hostEvidenceAccepted: options.hostEvidenceAccepted }),
      ...(options.sandboxIsolationAccepted === undefined ? {} : { sandboxIsolationAccepted: options.sandboxIsolationAccepted }),
      ...(options.sandboxEvidenceRef === undefined ? {} : { sandboxEvidenceRef: options.sandboxEvidenceRef }),
      ...(options.attestationVerificationAccepted === undefined ? {} : { attestationVerificationAccepted: options.attestationVerificationAccepted }),
      ...(options.attestationEvidenceRef === undefined ? {} : { attestationEvidenceRef: options.attestationEvidenceRef }),
      ...(options.evidenceRef === undefined ? {} : { evidenceRef: options.evidenceRef }),
      ...(options.releaseMode === undefined ? {} : { releaseMode: options.releaseMode }),
      ...(options.productionReleaseEvidence === undefined ? {} : { productionReleaseEvidence: options.productionReleaseEvidence }),
      ...(options.productionReleaseSignature === undefined ? {} : { productionReleaseSignature: options.productionReleaseSignature }),
      ...(options.productionReleaseArtifactPath === undefined ? {} : { productionReleaseArtifactPath: options.productionReleaseArtifactPath }),
      ...(options.pollIntervalMs === undefined ? {} : { pollIntervalMs: options.pollIntervalMs }),
      ...(options.protectedFilesystemRoots === undefined ? {} : { protectedFilesystemRoots: options.protectedFilesystemRoots }),
      ...(authorityPoller === undefined ? {} : { authorityPoller }),
      ...(options.authorityPollIntervalMs === undefined ? {} : { authorityPollIntervalMs: options.authorityPollIntervalMs })
    };
    const server = new RootHelperSnapshotServer(serverOptions);
    let statusServer: RootHelperSnapshotStatusIpcServer | undefined;
    let statusStateRef: { value: RootHelperSnapshotRuntimeState } | undefined;
    let statusMetadataRef: { value: Pick<RootHelperSnapshotStatusReadback, "sourceRevision" | "contractVersion" | "evidenceRef"> | undefined } | undefined;
    if (options.statusSocketPath !== undefined) {
      statusStateRef = { value: "stopped" };
      statusMetadataRef = { value: options.statusMetadata === undefined ? undefined : { ...options.statusMetadata } };
      statusServer = new RootHelperSnapshotStatusIpcServer({
        socketPath: options.statusSocketPath,
        authenticationKey: loaded.key.key,
        peerPolicy: options.peerPolicy,
        replayGuard: new MemoryRootHelperSnapshotStatusReplayGuard(),
        readStatus: () => {
          const metadata = statusMetadataRef!.value;
          if (metadata === undefined) throw new BrokerError("PRIVILEGE_DENIED", "Root-helper status metadata is not bound");
          return {
            component: "mac-operator-root-helper-snapshot",
            ...metadata,
            state: statusStateRef!.value,
            runtimeState: statusStateRef!.value,
            nativeTransportRequired: true,
            available: server.available,
            capability: server.capability
          };
        },
        authorizeStatus: () => {
          if (statusStateRef!.value !== "running") throw new BrokerError("PRIVILEGE_DENIED", "Root-helper snapshot status is not running");
        },
        now
      });
    }
    loaded.key.key.fill(0);
    loaded = undefined;
    return new RootHelperSnapshotRuntime(server, statusServer, statusStateRef, statusMetadataRef);
  } catch (error) {
    authorityPoller?.dispose?.();
    loaded?.key.key.fill(0);
    if (error instanceof RootHelperSnapshotRuntimeStartupError || error instanceof BrokerError) throw error;
    throw new RootHelperSnapshotRuntimeStartupError(
      "KEY_CONFIG_UNAVAILABLE",
      error instanceof Error ? error.message : "Root-helper snapshot key material could not be loaded"
    );
  }
}

function validateRuntimeOptions(options: RootHelperSnapshotRuntimeKeyMaterialOptions): void {
  const socketPaths = [
    options.socketPath,
    ...(options.statusSocketPath === undefined ? [] : [options.statusSocketPath]),
    options.brokerSocketPath,
    ...(options.authoritySocketPath === undefined ? [] : [options.authoritySocketPath]),
    ...(options.reservedSocketPaths ?? [])
  ];
  if (socketPaths.some((path) => !isCanonicalSocketPath(path)) || new Set(socketPaths).size !== socketPaths.length) {
    throw new RootHelperSnapshotRuntimeStartupError("SOCKET_INVALID", "Root-helper snapshot socket paths must be canonical and distinct");
  }
  if (options.statusMetadata !== undefined && options.statusSocketPath === undefined) {
    throw new RootHelperSnapshotRuntimeStartupError("SOCKET_INVALID", "Root-helper status metadata requires a status socket");
  }
  if (options.statusMetadata !== undefined) validateStatusMetadata(options.statusMetadata);
  if (options.sandboxIsolationAccepted !== undefined && typeof options.sandboxIsolationAccepted !== "boolean") {
    throw new RootHelperSnapshotRuntimeStartupError("SANDBOX_UNAVAILABLE", "Root-helper sandbox evidence flag is invalid");
  }
  if (options.attestationVerificationAccepted !== undefined && typeof options.attestationVerificationAccepted !== "boolean") {
    throw new RootHelperSnapshotRuntimeStartupError("ATTESTATION_VERIFICATION_UNAVAILABLE", "Root-helper attestation verification flag is invalid");
  }
  for (const [label, value] of [["sandbox", options.sandboxEvidenceRef], ["attestation", options.attestationEvidenceRef], ["helper", options.evidenceRef]] as const) {
    if (value !== undefined && (typeof value !== "string" || !/^[A-Za-z0-9._:/-]{1,256}$/u.test(value))) {
      throw new RootHelperSnapshotRuntimeStartupError(label === "attestation" ? "ATTESTATION_VERIFICATION_UNAVAILABLE" : "SANDBOX_UNAVAILABLE", `Root-helper ${label} evidence reference is invalid`);
    }
  }
  const peer = options.peerPolicy;
  if (!Number.isSafeInteger(peer.expectedUid) || peer.expectedUid < 1 ||
      (peer.expectedGid !== undefined && (!Number.isSafeInteger(peer.expectedGid) || peer.expectedGid < 0)) ||
      peer.allowedProcessIdentity === undefined ||
      !Number.isSafeInteger(peer.allowedProcessIdentity.pid) || peer.allowedProcessIdentity.pid < 1 ||
      !Number.isSafeInteger(peer.allowedProcessIdentity.startTimeMicros) || peer.allowedProcessIdentity.startTimeMicros < 1) {
    throw new RootHelperSnapshotRuntimeStartupError("PEER_POLICY_INVALID", "Root-helper snapshot runtime requires a named non-root Broker identity");
  }
}

function isCanonicalSocketPath(path: unknown): path is string {
  return typeof path === "string" && isAbsolute(path) && resolve(path) === path && !path.includes("\0") && path.length <= 1_024;
}

function validateStatusMetadata(
  metadata: Pick<RootHelperSnapshotStatusReadback, "sourceRevision" | "contractVersion" | "evidenceRef">
): void {
  if (!/^[0-9a-f]{7,64}$/u.test(metadata.sourceRevision) ||
      !/^v?\d+\.\d+(?:\.\d+)?(?:[-+].*)?$/u.test(metadata.contractVersion) ||
      (metadata.evidenceRef !== undefined && !/^[A-Za-z0-9._:/-]{1,256}$/u.test(metadata.evidenceRef))) {
    throw new RootHelperSnapshotRuntimeStartupError("SOCKET_INVALID", "Root-helper status metadata is invalid");
  }
}
