import type { BrokerStore } from "./persistence.js";
import {
  DescriptorSnapshotAttestationSigner,
  DescriptorSnapshotAttestationVerifier,
  DescriptorSnapshotRegistry
} from "./descriptor-snapshot-attestation.js";
import {
  NativeRootHelperSnapshotTransport,
  type NativeRootHelperSnapshotTransportOptions
} from "./root-helper-snapshot-transport.js";
import {
  DisabledRootHelperSnapshotTransport,
  RootHelperSnapshotTaskExecutor,
  type RootHelperSnapshotCapability
} from "./root-helper-snapshot.js";
import {
  RootHelperSnapshotTaskRunner,
  type RootHelperSnapshotTaskRunnerOptions,
  type TaskIsolationProof
} from "./task-runner.js";
import {
  captureLaunchdRootHelperProcessIdentity,
  type LaunchdRootHelperIdentityCommandExecutor
} from "./root-helper-snapshot-service.js";
import { PrivilegedHelperKeyManager } from "./privileged-helper-keyring.js";
import type { CodeSignatureExpectation } from "./macos-install-plan.js";
import type { RootHelperSnapshotReleaseEvidence } from "./root-helper-snapshot-release.js";

export interface RootHelperSnapshotTaskRunnerStartupOptions {
  /** Explicit opt-in; omitted and false both remain unavailable. */
  enabled?: boolean;
  /** Independent host evidence gate; request arguments cannot provide it. */
  hostEvidenceAccepted?: boolean;
  /** Explicit release provenance mode for the exact native root-helper executable. */
  releaseMode?: "development-probe" | "production";
  /** Required with production mode; generated by the read-only release preflight. */
  productionReleaseEvidence?: RootHelperSnapshotReleaseEvidence;
  /** Required with production mode; pins the Developer ID identity. */
  productionReleaseSignature?: CodeSignatureExpectation;
  /** Required with production mode; exact native helper executable path. */
  productionReleaseArtifactPath?: string;
  isolationProof?: TaskIsolationProof | null;
  /** Host-owned descriptor signing and verification keys. */
  signer?: DescriptorSnapshotAttestationSigner;
  verifier?: DescriptorSnapshotAttestationVerifier;
  /** Independently accepted root-helper capability evidence. */
  capability?: RootHelperSnapshotCapability;
  /** Broker-side endpoint; the root helper owns the listening socket. */
  socketPath?: string;
  /** Used to reject endpoint reuse before native transport construction. */
  brokerSocketPath?: string;
  /** Protected helper key configuration; raw key bytes are never accepted. */
  helperKeyConfigPath?: string;
  rootHelperServiceId?: string;
  rootHelperCommandExecutor?: LaunchdRootHelperIdentityCommandExecutor;
  now?: () => number;
  timeoutMs?: number;
  snapshotLifetimeMs?: number;
  maxSnapshots?: number;
}

export interface RootHelperSnapshotTaskRunnerStartupAssembly {
  readonly taskRunner: RootHelperSnapshotTaskRunner;
  readonly snapshotRegistry: DescriptorSnapshotRegistry;
  readonly executor: RootHelperSnapshotTaskExecutor;
  readonly transport: NativeRootHelperSnapshotTransport | DisabledRootHelperSnapshotTransport;
}

/**
 * Assembles the Broker-side root-helper task boundary. The default branch
 * constructs only disabled components. The enabled branch restores the
 * persisted helper key, binds the exact root LaunchDaemon identity, and then
 * constructs the native transport; it never accepts raw key material.
 */
export async function createRootHelperSnapshotTaskRunnerFromActiveKeyConfig(options: {
  store: BrokerStore;
  startup: RootHelperSnapshotTaskRunnerStartupOptions;
}): Promise<RootHelperSnapshotTaskRunnerStartupAssembly> {
  const startup = options.startup;
  const evidenceAccepted = startup.enabled === true && startup.hostEvidenceAccepted === true;
  const snapshotRegistry = new DescriptorSnapshotRegistry({
    enabled: evidenceAccepted,
    ...(startup.signer === undefined ? {} : { signer: startup.signer }),
    ...(startup.verifier === undefined ? {} : { verifier: startup.verifier }),
    ...(startup.now === undefined ? {} : { now: startup.now }),
    ...(startup.snapshotLifetimeMs === undefined ? {} : { lifetimeMs: startup.snapshotLifetimeMs }),
    ...(startup.maxSnapshots === undefined ? {} : { maxSnapshots: startup.maxSnapshots })
  });

  if (!evidenceAccepted) {
    const transport = new DisabledRootHelperSnapshotTransport();
    const executor = new RootHelperSnapshotTaskExecutor({ transport });
    return {
      taskRunner: createTaskRunner(startup, executor, snapshotRegistry),
      snapshotRegistry,
      executor,
      transport
    };
  }

  const socketPath = requireString(startup.socketPath, "root-helper snapshot socket path");
  const brokerSocketPath = requireString(startup.brokerSocketPath, "Broker socket path");
  if (socketPath === brokerSocketPath) {
    await snapshotRegistry.close();
    throw new Error("Root-helper snapshot task socket must be separate from the Broker socket");
  }
  const helperKeyConfigPath = requireString(startup.helperKeyConfigPath, "root-helper snapshot key config path");
  const rootHelperServiceId = requireString(startup.rootHelperServiceId, "root-helper snapshot service identity");
  if (!(startup.signer instanceof DescriptorSnapshotAttestationSigner) ||
      !(startup.verifier instanceof DescriptorSnapshotAttestationVerifier)) {
    await snapshotRegistry.close();
    throw new Error("Enabled root-helper snapshot tasks require host-owned descriptor signing and verification keys");
  }
  if (startup.capability === undefined) {
    await snapshotRegistry.close();
    throw new Error("Enabled root-helper snapshot tasks require independent capability evidence");
  }

  const now = startup.now ?? Date.now;
  const keyManager = new PrivilegedHelperKeyManager(helperKeyConfigPath, options.store, now);
  let transport: NativeRootHelperSnapshotTransport | undefined;
  try {
    const rootHelperIdentity = await captureLaunchdRootHelperProcessIdentity({
      rootHelperServiceId,
      ...(startup.rootHelperCommandExecutor === undefined ? {} : { commandExecutor: startup.rootHelperCommandExecutor })
    });
    await keyManager.restore();
    const authenticationKey = keyManager.assertUsable();
    try {
      const transportOptions: NativeRootHelperSnapshotTransportOptions = {
        socketPath,
        authenticationKey,
        capability: startup.capability,
        peerPolicy: { expectedUid: 0, allowedProcessIdentity: rootHelperIdentity },
        ...(startup.now === undefined ? {} : { now: startup.now }),
        ...(startup.timeoutMs === undefined ? {} : { timeoutMs: startup.timeoutMs })
      };
      transport = new NativeRootHelperSnapshotTransport(transportOptions);
    } finally {
      authenticationKey.fill(0);
    }
  } catch (error) {
    keyManager.dispose();
    await snapshotRegistry.close().catch(() => undefined);
    throw error;
  }
  keyManager.dispose();

  const executor = new RootHelperSnapshotTaskExecutor({
    enabled: true,
    hostEvidenceAccepted: true,
    ...(startup.releaseMode === undefined ? {} : { releaseMode: startup.releaseMode }),
    ...(startup.productionReleaseEvidence === undefined ? {} : { productionReleaseEvidence: startup.productionReleaseEvidence }),
    ...(startup.productionReleaseSignature === undefined ? {} : { productionReleaseSignature: startup.productionReleaseSignature }),
    ...(startup.productionReleaseArtifactPath === undefined ? {} : { productionReleaseArtifactPath: startup.productionReleaseArtifactPath }),
    transport,
    attestationVerifier: startup.verifier
  });
  const taskRunner = createTaskRunner(startup, executor, snapshotRegistry);
  if (!taskRunner.available) {
    await taskRunner.close().catch(() => undefined);
    throw new Error("Enabled root-helper snapshot task boundary did not satisfy the host availability gate");
  }
  return { taskRunner, snapshotRegistry, executor, transport };
}

function createTaskRunner(
  startup: RootHelperSnapshotTaskRunnerStartupOptions,
  executor: RootHelperSnapshotTaskExecutor,
  snapshotRegistry: DescriptorSnapshotRegistry
): RootHelperSnapshotTaskRunner {
  const runnerOptions: RootHelperSnapshotTaskRunnerOptions = {
    ...(startup.enabled === undefined ? {} : { enabled: startup.enabled }),
    ...(startup.hostEvidenceAccepted === undefined ? {} : { hostEvidenceAccepted: startup.hostEvidenceAccepted }),
    ...(startup.isolationProof === undefined ? {} : { isolationProof: startup.isolationProof }),
    executor,
    snapshotRegistry
  };
  return new RootHelperSnapshotTaskRunner(runnerOptions);
}

function requireString(value: string | undefined, label: string): string {
  if (typeof value !== "string" || value.length === 0) throw new Error(`Enabled ${label} is required`);
  return value;
}
